version: '3.7'

services:
  wordpress:
    image: wordpress:6.4
    ports:
      - 4231:80
    volumes:
      - wordpress:/var/www/html

  database:
    image: mysql:8.0
    volumes:
      - mysqldb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpadmin
      MYSQL_PASSWORD: wpadmin@123


volumes:
  wordpress:
  mysqldb:
